"""
Atlas Agent Events

Defines events generated by agents.
"""

from enum import Enum


class AgentEvents(str, Enum):
    """
    Agent lifecycle events.
    """

    CREATED = "agent.created"

    STARTED = "agent.started"

    PAUSED = "agent.paused"

    STOPPED = "agent.stopped"

    ACTION = "agent.action"